import pandas as pd
import pytest

from src.analyzer import (
    AnalysisResult,
    CorrelationResult,
    EduDataAnalyzer,
    TrendResult,
    compute_bayes_factor_correlation,
)
from src.fetchers.base import EducationDataset
from src.pdf.pdf_generator import EduPaperPdfGenerator
from src.reporter import EduReportBuilder


def test_compute_bayes_factor_correlation_values():
    """Verifies that JZS Bayes Factor returns accurate results and interpretations."""
    # N <= 2 edge case
    bf10, interp = compute_bayes_factor_correlation(0.5, 2)
    assert bf10 == 1.0
    assert "N数不足" in interp

    # Strong correlation: r=0.6, n=20
    bf10, interp = compute_bayes_factor_correlation(0.6, 20)
    assert bf10 > 3.0
    assert "H1支持" in interp

    # Very strong correlation: r=0.8, n=30
    bf10, interp = compute_bayes_factor_correlation(0.8, 30)
    assert bf10 > 100.0
    assert "極めて強い証拠" in interp

    # Null hypothesis support: r=0.01, n=60
    bf10, interp = compute_bayes_factor_correlation(0.01, 60)
    assert bf10 < 1.0 / 3.0
    assert "H0支持" in interp

    # Perfect correlation boundary
    bf10, interp = compute_bayes_factor_correlation(1.0, 15)
    assert bf10 >= 99999.0
    assert "H1支持" in interp


def test_analyzer_integrates_bayes_factor():
    """Verifies DataAnalyzer calculates BF10 for trends and correlations."""
    data = {
        "year": [2018, 2019, 2020, 2021, 2022, 2023],
        "score_a": [50.0, 55.0, 60.0, 65.0, 70.0, 75.0],
        "score_b": [80.0, 78.0, 75.0, 72.0, 68.0, 65.0],
    }
    df = pd.DataFrame(data)
    dataset = EducationDataset(
        id="test_bayes_ds",
        title="テスト教育データ",
        category="math",
        df=df,
        source_name="文部科学省",
        source_url="https://example.com",
        time_col="year",
        metrics=["score_a", "score_b"],
        unit="点",
        region="全国",
        description="テスト用データセット",
    )

    analyzer = EduDataAnalyzer()
    res = analyzer.analyze(dataset)

    # Check trends
    assert len(res.trends) >= 2
    for tr in res.trends:
        assert tr.bf10 is not None
        assert tr.bf10 > 0
        assert tr.bf_interpretation is not None
        assert len(tr.bf_interpretation) > 0

    # Check correlations
    assert len(res.correlations) >= 1
    cr = res.correlations[0]
    assert cr.bf10 is not None
    assert cr.bf10 > 0
    assert cr.bf_interpretation is not None

    # Check key insights contain BF10
    has_bf_insight = any("BF₁₀" in ins for ins in res.key_insights)
    assert has_bf_insight


def test_reporter_tables_include_bayes_factor():
    """Verifies that Markdown and HTML tables in reporter include BF10 columns and badges."""
    tr = TrendResult(
        metric="score_a",
        group_name=None,
        start_time="2018",
        start_val=50.0,
        end_time="2023",
        end_val=75.0,
        diff=25.0,
        pct_change=50.0,
        cagr=8.45,
        slope=5.0,
        r_squared=1.0,
        bf10=45.2,
        bf_interpretation="非常に強い証拠（H1支持）",
    )
    cr = CorrelationResult(
        metric_x="score_a",
        metric_y="score_b",
        pearson_r=-0.99,
        p_value=0.0001,
        interpretation="極めて強い負の相関",
        bf10=150.0,
        bf_interpretation="極めて強い証拠（H1支持）",
    )
    analysis = AnalysisResult(
        dataset_id="test_ds",
        dataset_title="テストデータ",
        unit="点",
        sample_size=6,
        descriptive_stats={},
        trends=[tr],
        correlations=[cr],
        rankings={},
        key_insights=[],
        raw_df=pd.DataFrame(),
    )
    dataset = EducationDataset(
        id="test_ds",
        title="テストデータ",
        category="math",
        df=pd.DataFrame(),
        source_name="文部科学省",
        source_url="https://example.com",
        time_col="year",
        metrics=["score_a", "score_b"],
        unit="点",
        region="全国",
        description="テスト用データセット",
    )

    reporter = EduReportBuilder()
    md_tr, html_tr = reporter._build_trend_tables(dataset, analysis)
    assert "ベイズファクター (BF₁₀)" in md_tr
    assert "45.20" in md_tr
    assert "ベイズファクター (BF₁₀)" in html_tr
    assert "45.20" in html_tr

    md_cr, html_cr = reporter._build_correlation_tables(analysis)
    assert "ベイズファクター (BF₁₀)" in md_cr
    assert "150.00" in md_cr
    assert "ベイズファクター (BF₁₀)" in html_cr
    assert "150.00" in html_cr


def test_generated_python_script_includes_bayes_factor():
    """Verifies that the reproducible Python script generated by reporter defines calc_bf10_correlation."""
    df = pd.DataFrame({"year": [2020, 2021], "val": [10, 20]})
    dataset = EducationDataset(
        id="test_ds",
        title="テストデータ",
        category="math",
        df=df,
        source_name="文部科学省",
        source_url="https://example.com",
        time_col="year",
        metrics=["val"],
        unit="点",
        region="全国",
        description="テスト用データセット",
    )
    reporter = EduReportBuilder()
    analysis = AnalysisResult(
        dataset_id="test_ds",
        dataset_title="テストデータ",
        unit="点",
        sample_size=2,
        descriptive_stats={},
        trends=[],
        correlations=[],
        rankings={},
        key_insights=[],
        raw_df=df,
    )
    code = reporter._generate_python_analysis_code(dataset, analysis)
    assert "def calc_bf10_correlation(r, n):" in code
    assert "BF₁₀" in code


def test_pdf_secondary_table_includes_bayes_factor():
    """Verifies that AcademicPDFGenerator._build_secondary_table includes BF10 for trends and correlations."""
    generator = EduPaperPdfGenerator()
    dataset = EducationDataset(
        id="test_ds",
        title="テストデータ",
        category="math",
        df=pd.DataFrame(),
        source_name="文部科学省",
        source_url="https://example.com",
        time_col="year",
        metrics=["score_a"],
        unit="点",
        region="全国",
        description="テスト用データセット",
    )

    # Trend case
    tr = TrendResult(
        metric="score_a",
        group_name=None,
        start_time="2018",
        start_val=50.0,
        end_time="2023",
        end_val=75.0,
        diff=25.0,
        pct_change=50.0,
        cagr=8.45,
        slope=5.0,
        r_squared=0.99,
        bf10=18.5,
        bf_interpretation="強い証拠（H1支持）",
    )
    analysis_trend = AnalysisResult(
        dataset_id="test_ds",
        dataset_title="テストデータ",
        unit="点",
        sample_size=6,
        descriptive_stats={},
        trends=[tr],
        correlations=[],
        rankings={},
        key_insights=[],
        raw_df=pd.DataFrame(),
    )
    caption, table, note = generator._build_secondary_table(dataset, analysis_trend)
    assert "ベイズ分析" in caption
    assert "BF₁₀" in note

    # Correlation case
    cr = CorrelationResult(
        metric_x="score_a",
        metric_y="score_b",
        pearson_r=0.65,
        p_value=0.01,
        interpretation="強い正相関",
        bf10=8.2,
        bf_interpretation="中程度の証拠（H1支持）",
    )
    analysis_corr = AnalysisResult(
        dataset_id="test_ds",
        dataset_title="テストデータ",
        unit="点",
        sample_size=6,
        descriptive_stats={},
        trends=[],
        correlations=[cr],
        rankings={},
        key_insights=[],
        raw_df=pd.DataFrame(),
    )
    caption_c, table_c, note_c = generator._build_secondary_table(dataset, analysis_corr)
    assert "ベイズファクター" in caption_c
    assert "BF₁₀" in note_c


def test_format_bayes_factor_short_interpretation():
    """Verifies that short BF interpretations match standard Bayesian evidence categories."""
    from src.utils import format_bayes_factor_short_interpretation

    assert format_bayes_factor_short_interpretation(154.46) == "極めて強い"
    assert format_bayes_factor_short_interpretation(45.0) == "非常に強い"
    assert format_bayes_factor_short_interpretation(12.0) == "強い証拠"
    assert format_bayes_factor_short_interpretation(5.0) == "中程度"
    assert format_bayes_factor_short_interpretation(2.12) == "弱い証拠"
    assert format_bayes_factor_short_interpretation(2.08) == "弱い証拠"
    assert format_bayes_factor_short_interpretation(0.2) == "中程度(H0)"
    assert format_bayes_factor_short_interpretation(0.05) == "強い(H0)"
    assert format_bayes_factor_short_interpretation(0.01) == "極強(H0)"
    assert format_bayes_factor_short_interpretation(None) == "-"


def test_pdf_correlation_table_correct_bf_column():
    """Verifies that PDF Table 2 header is 'BF証拠判定' and maps 2.12 to '弱い証拠'."""
    generator = EduPaperPdfGenerator()
    cr1 = CorrelationResult(
        metric_x="ICT活用指導肯定率",
        metric_y="批判的思考促進自己効力感",
        pearson_r=0.724,
        p_value=0.0422,
        interpretation="強い正の相関",
        bf10=2.12,
        bf_interpretation="弱い証拠（H1支持: 逸話的）",
    )
    cr2 = CorrelationResult(
        metric_x="批判的思考促進自己効力感",
        metric_y="教員間協働指導実施率",
        pearson_r=0.952,
        p_value=0.0003,
        interpretation="極めて強い正の相関",
        bf10=154.46,
        bf_interpretation="極めて強い証拠（H1支持）",
    )
    analysis = AnalysisResult(
        dataset_id="test_ds",
        dataset_title="テストデータ",
        unit="%",
        sample_size=8,
        descriptive_stats={},
        trends=[],
        correlations=[cr1, cr2],
        rankings={},
        key_insights=[],
        raw_df=pd.DataFrame(),
    )
    dataset = EducationDataset(
        id="test_ds",
        title="テストデータ",
        category="math",
        df=pd.DataFrame(),
        source_name="OECD",
        source_url="https://example.com",
        time_col="year",
        metrics=["m1"],
        unit="%",
        region="global",
        description="テスト",
    )
    caption, table, note = generator._build_secondary_table(dataset, analysis)
    headers = [p.text for p in table._cellvalues[0]]
    assert "BF証拠判定" in headers
    assert "<i>BF</i><sub>10</sub>" in headers

    row1 = [p.text for p in table._cellvalues[1]]
    assert row1[4] == "2.12"
    assert row1[5] == "弱い証拠"  # NOT "極めて強い"!

    row2 = [p.text for p in table._cellvalues[2]]
    assert row2[4] == "154.46"
    assert row2[5] == "極めて強い"

